#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/ayu_dark.toml"]
import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/gruvbox_dark.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/gruvbox_light.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/nordic.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/everforest_dark_hard.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/catppuccin_macchiato.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/solarized_light.toml"]
#import = ["/home/eytan/.config/alacritty/random-themes/melange_dark.toml"]
#import = ["/home/eytan/.config/alacritty/tempus-themes/tempus_autumn.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/everforest_dark.toml"]
[font]
size = 10.5

[font.normal]
family = "Iosevka"
style = "monospace"

[scrolling]
history = 100000

#[schemes.everforest_dark_hard.bright]
#black = "#475258"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_hard.normal]
#black = "#414b50"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_hard.primary]
#background = "#272e33"
#foreground = "#d3c6aa"
#
#[schemes.everforest_dark_medium.bright]
#black = "#475258"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_medium.normal]
#black = "#475258"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_medium.primary]
#background = "#2d353b"
#foreground = "#d3c6aa"
#
#[schemes.everforest_dark_soft.bright]
#black = "#4d5960"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_soft.normal]
#black = "#4d5960"
#blue = "#7fbbb3"
#cyan = "#83c092"
#green = "#a7c080"
#magenta = "#d699b6"
#red = "#e67e80"
#white = "#d3c6aa"
#yellow = "#dbbc7f"
#
#[schemes.everforest_dark_soft.primary]
#background = "#333c43"
#foreground = "#d3c6aa"
#
#[schemes.everforest_light_hard.bright]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#e8e5d5"
#yellow = "#dfa000"
#
#[schemes.everforest_light_hard.normal]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#e8e5d5"
#yellow = "#dfa000"
#
#[schemes.everforest_light_hard.primary]
#background = "#fffbef"
#foreground = "#5c6a72"
#
#[schemes.everforest_light_medium.bright]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#e0dcc7"
#yellow = "#dfa000"
#
#[schemes.everforest_light_medium.normal]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#e0dcc7"
#yellow = "#dfa000"
#
#[schemes.everforest_light_medium.primary]
#background = "#fdf6e3"
#foreground = "#5c6a72"
#
#[schemes.everforest_light_soft.bright]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#d8d3ba"
#yellow = "#dfa000"
#
#[schemes.everforest_light_soft.normal]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#d8d3ba"
#yellow = "#dfa000"
#
#[schemes.everforest_light_soft.primary]
#background = "#f3ead3"
#foreground = "#5c6a72"
#
#[schemes.gruvbox_material_hard_dark.bright]
#black = "0x32302f"
#blue = "0x7daea3"
#cyan = "0x89b482"
#green = "0xa9b665"
#magenta = "0xd3869b"
#red = "0xea6962"
#white = "0xd4be98"
#yellow = "0xd8a657"
#
#[schemes.gruvbox_material_hard_dark.normal]
#black = "0x32302f"
#blue = "0x7daea3"
#cyan = "0x89b482"
#green = "0xa9b665"
#magenta = "0xd3869b"
#red = "0xea6962"
#white = "0xd4be98"
#yellow = "0xd8a657"
#
#[schemes.gruvbox_material_hard_dark.primary]
#background = "0x1d2021"
#foreground = "0xd4be98"
#
#[schemes.gruvbox_material_hard_light.bright]
#black = "0x654735"
#blue = "0x45707a"
#cyan = "0x4c7a5d"
#green = "0x6c782e"
#magenta = "0x945e80"
#red = "0xc14a4a"
#white = "0xf2e5bc"
#yellow = "0xb47109"
#
#[schemes.gruvbox_material_hard_light.normal]
#black = "0x654735"
#blue = "0x45707a"
#cyan = "0x4c7a5d"
#green = "0x6c782e"
#magenta = "0x945e80"
#red = "0xc14a4a"
#white = "0xf2e5bc"
#yellow = "0xb47109"
#
#[schemes.gruvbox_material_hard_light.primary]
#background = "0xf9f5d7"
#foreground = "0x654735"
#
#[schemes.gruvbox_material_medium_dark.bright]
#black = "0x3c3836"
#blue = "0x7daea3"
#cyan = "0x89b482"
#green = "0xa9b665"
#magenta = "0xd3869b"
#red = "0xea6962"
#white = "0xd4be98"
#yellow = "0xd8a657"
#
#[schemes.gruvbox_material_medium_dark.normal]
#black = "0x3c3836"
#blue = "0x7daea3"
#cyan = "0x89b482"
#green = "0xa9b665"
#magenta = "0xd3869b"
#red = "0xea6962"
#white = "0xd4be98"
#yellow = "0xd8a657"
#
#[schemes.gruvbox_material_medium_dark.primary]
#background = "0x282828"
#foreground = "0xd4be98"
#
#[schemes.gruvbox_material_medium_light.bright]
#black = "0x654735"
#blue = "0x45707a"
#cyan = "0x4c7a5d"
#green = "0x6c782e"
#magenta = "0x945e80"
#red = "0xc14a4a"
#white = "0xeee0b7"
#yellow = "0xb47109"
#
#[schemes.gruvbox_material_medium_light.normal]
#black = "0x654735"
#blue = "0x45707a"
#cyan = "0x4c7a5d"
#green = "0x6c782e"
#magenta = "0x945e80"
#red = "0xc14a4a"
#white = "0xeee0b7"
#yellow = "0xb47109"
#
#[schemes.gruvbox_material_medium_light.primary]
#background = "0xfbf1c7"
#foreground = "0x654735"
#
#[schemes.gruvbox_material_soft_dark.bright]
#black = "0x45403d"
#blue = "0x7daea3"
#cyan = "0x89b482"
#green = "0xa9b665"
#magenta = "0xd3869b"
#red = "0xea6962"
#white = "0xd4be98"
#yellow = "0xd8a657"
#
#[schemes.gruvbox_material_soft_dark.normal]
#black = "0x45403d"
#blue = "0x7daea3"
#cyan = "0x89b482"
#green = "0xa9b665"
#magenta = "0xd3869b"
#red = "0xea6962"
#white = "0xd4be98"
#yellow = "0xd8a657"
#
#[schemes.gruvbox_material_soft_dark.primary]
#background = "0x32302f"
#foreground = "0xd4be98"
#
#[schemes.gruvbox_material_soft_light.bright]
#black = "0x654735"
#blue = "0x45707a"
#cyan = "0x4c7a5d"
#green = "0x6c782e"
#magenta = "0x945e80"
#red = "0xc14a4a"
#white = "0xe6d5ae"
#yellow = "0xb47109"
#
#[schemes.gruvbox_material_soft_light.normal]
#black = "0x654735"
#blue = "0x45707a"
#cyan = "0x4c7a5d"
#green = "0x6c782e"
#magenta = "0x945e80"
#red = "0xc14a4a"
#white = "0xe6d5ae"
#yellow = "0xb47109"
#
#[schemes.gruvbox_material_soft_light.primary]
#background = "0xf2e5bc"
#foreground = "0x654735"
#
#[schemes.nord.bright]
#black = "#4c566a"
#blue = "#81a1c1"
#cyan = "#8fbcbb"
#green = "#a3be8c"
#magenta = "#b48ead"
#red = "#bf616a"
#white = "#eceff4"
#yellow = "#ebcb8b"
#
#[schemes.nord.cursor]
#cursor = "#d8dee9"
#text = "#2e3440"
#
#[schemes.nord.dim]
#black = "#373e4d"
#blue = "#68809a"
#cyan = "#6d96a5"
#green = "#809575"
#magenta = "#8c738c"
#red = "#94545d"
#white = "#aeb3bb"
#yellow = "#b29e75"
#
#[schemes.nord.normal]
#black = "#3b4252"
#blue = "#81a1c1"
#cyan = "#88c0d0"
#green = "#a3be8c"
#magenta = "#b48ead"
#red = "#bf616a"
#white = "#e5e9f0"
#yellow = "#ebcb8b"
#
#[schemes.nord.primary]
#background = "#222630"
#dim_foreground = "#a5abb6"
#foreground = "#d8dee9"
#
#[schemes.nord.search."colors.footer_bar"]
#background = "#434c5e"
#foreground = "#d8dee9"
#
#[schemes.nord.search.matches]
#background = "#88c0d0"
#foreground = "CellBackground"
#
#[schemes.nord.selection]
#background = "#4c566a"
#text = "CellForeground"
#
#[schemes.nord.vi_mode_cursor]
#cursor = "#d8dee9"
#text = "#2e3440"
#
#[[schemes.terafox.indexed_colors]]
#color = "0xff8349"
#index = 16
#
#[[schemes.terafox.indexed_colors]]
#color = "0xcb7985"
#index = 17
#
#[schemes.terafox.bright]
#black = "0x4e5157"
#blue = "0x73a3b7"
#cyan = "0xafd4de"
#green = "0x8eb2af"
#magenta = "0xb97490"
#red = "0xeb746b"
#white = "0xeeeeee"
#yellow = "0xfdb292"
#
#[schemes.terafox.normal]
#black = "0x2f3239"
#blue = "0x5a93aa"
#cyan = "0xa1cdd8"
#green = "0x7aa4a1"
#magenta = "0xad5c7c"
#red = "0xe85c51"
#white = "0xebebeb"
#yellow = "0xfda47f"
#
#[schemes.terafox.primary]
#background = "0x152528"
#foreground = "0xe6eaea"
