[font]
size = 14

[font.normal]
family = "Iosevka"
style = "monospace"

[scrolling]
history = 100000

[general]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/gruvbox_dark.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/spacegray.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/citylights.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/autumn.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/terafox.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/everforest_dark.toml"]
import = ["/home/eytan/.config/alacritty/everviolet/themes/evergarden-fall-snow.toml"]

