[font]
size = 14

[font.normal]
family = "Iosevka"
style = "monospace"

[scrolling]
history = 100000

[general]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/gruvbox_light.toml"]
import = ["/home/eytan/.config/alacritty/random-themes/tknl.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/everforest_light.toml"]
