[font]
size = 14

[font.normal]
family = "Iosevka"
style = "monospace"

[scrolling]
history = 100000

[general]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/gruvbox_light.toml"]
#import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/ashes_light.toml"]
import = ["/home/eytan/.config/alacritty/zenbones-themes/zenwritten_light.toml"]
