[font]
size = 13

[font.normal]
family = "Iosevka"
style = "monospace"

[scrolling]
history = 100000

[general]
import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/everforest_dark.toml"]
