[font]
size = 11

[font.normal]
family = "Iosevka"
style = "monospace"

[scrolling]
history = 100000

[general]
import = ["/home/eytan/.config/alacritty/alacritty-colorscheme/themes/gruvbox_light.toml"]
