preload = /home/eytan/Pictures/Wallpapers/starry-sky.png
wallpaper = eDP-1,/home/eytan/Pictures/Wallpapers/starry-sky.png
wallpaper = DP-2,/home/eytan/Pictures/Wallpapers/starry-sky.png
wallpaper = HDMI-A-1,/home/eytan/Pictures/Wallpapers/starry-sky.png

wallpaper {
    monitor = eDP-1
    path = /home/eytan/Pictures/Wallpapers/starry-sky.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/eytan/Pictures/Wallpapers/starry-sky.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/eytan/Pictures/Wallpapers/starry-sky.png
    fit_mode = cover
}

splash = false
ipc = off
